"""empty message

Revision ID: 43517924900e
Revises: 834b1a697901
Create Date: 2023-02-25 11:58:31.662573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43517924900e'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    # ### end Alembic commands ###
