"""empty message

Revision ID: 5e587200c789
Revises: cd0a93abe073
Create Date: 2023-02-25 15:49:26.997322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e587200c789'
down_revision = 'cd0a93abe073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('archive', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('archive', sa.Column('postId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_column('archive', 'archivedByUser')
    op.drop_column('archive', 'postID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('postID', sa.INTEGER(), nullable=True))
    op.add_column('archive', sa.Column('archivedByUser', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'archive', 'post', ['postID'], ['id'])
    op.create_foreign_key(None, 'archive', 'user', ['archivedByUser'], ['id'])
    op.drop_column('archive', 'postId')
    op.drop_column('archive', 'userId')
    op.drop_column('archive', 'id')
    # ### end Alembic commands ###
