"""empty message

Revision ID: 6154435a44f1
Revises: 7ea5d8456e8d
Create Date: 2023-03-10 16:07:21.804212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6154435a44f1'
down_revision = '7ea5d8456e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilePicture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilePicture')
    # ### end Alembic commands ###
