"""empty message

Revision ID: 7ea5d8456e8d
Revises: cd0a93abe073
Create Date: 2023-02-25 20:55:09.901802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea5d8456e8d'
down_revision = 'cd0a93abe073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivedPosts',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], )
    )
    op.drop_table('archive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('postID', sa.INTEGER(), nullable=True),
    sa.Column('archivedByUser', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['archivedByUser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['postID'], ['post.id'], )
    )
    op.drop_table('archivedPosts')
    # ### end Alembic commands ###
