"""empty message

Revision ID: cd0a93abe073
Revises: 834b1a697901
Create Date: 2023-02-25 15:02:28.898965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0a93abe073'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('postID', sa.Integer(), nullable=True),
    sa.Column('archivedByUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archivedByUser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['postID'], ['post.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')
    # ### end Alembic commands ###
